### ISSUE TITLE
Where to download the Power-AI-Engine SDK

### ISSUE THREAD

**Issue by shengwenliang** [IBM/AccDNN#11]
Dear:
      Hi, I want to use this project to deploy the DNN to my FPGA board (x7zc045). However, I can not find the power AI engine SDK. so, could you tell me where can i download the power ai engine SDK? Thanks.

**Comment by iordanouki** [comment]
Hi, I have the same issue! Can you please tell us more about the powerAI engine SDK?
Best,
Kostas.

**Comment by shengwenliang** [comment]
Hi, I only find this engine in https://www.ibm.com/support/knowledgecenter/en/SSRU69_1.1.2/base/vision_inference_edge.html
however, I didn't try it because it needs the power server.

**Comment by iordanouki** [comment]
> Hi, I only find this engine in https://www.ibm.com/support/knowledgecenter/en/SSRU69_1.1.2/base/vision_inference_edge.html
> however, I didn't try it because it needs the power server.

Thanks for your reply! Yes I found the same source.

However you can  go with the choice of not using the power AI engine and create accelerator IPs on vivado without the power AI engine SDK support.

Best,
Kostas.

**Comment by Junsong-Wang** [comment]
Power AI engine SDK is only required when you use the IBM POWER server as the host to communicate with the attached FPGA.
